ALTER TABLE kunden ADD COLUMN IF NOT EXISTS zustaendig_id UUID
  REFERENCES profiles(id) ON DELETE SET NULL;

ALTER TABLE pipeline ADD COLUMN IF NOT EXISTS zustaendig_id UUID
  REFERENCES profiles(id) ON DELETE SET NULL;
